language: elixir
elixir:
  - '1.5'
  - '1.6'
otp_release:
  - '19.0'
  - '20.0'
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
  - mix format --check-formatted
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix coveralls.travis
  - MIX_ENV=docs mix inch.report
