language: erlang
otp_release:
        - 17.1
before_install:
        - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.1/Precompiled.zip
        - unzip -d elixir Precompiled.zip
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"
after_success:
        - "mix compile && mix coveralls.travis"
